name: testexe

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: build with pyinstaller
      run: |
        pyinstaller main.py
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
       name: exesnik
       path: D:\a\testes\testes\build\main\main.exe
    - name: Download artifact
      uses: aochmann/actions-download-artifact@1.0.4
    - name: Simple commit
      uses: zwaldowski/git-commit-action@v1
      with:
       commit_message: наконецто
    - name: action-push
      uses: ludeeus/action-push@0.0.1
    
    
